name: socialverse
description: SocialVerse is a blazing a new social frontier of long-form mobile videos.A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.8.3+160
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  # google_sign_in: ^7.0.0
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^5.2.0

  cached_network_image: ^3.2.0
  image_cropper: ^9.1.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  screenshot: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  web_socket_channel: ^3.0.3

  intl: ^0.20.2
  uuid: ^4.5.1
  timeago: ^3.2.0
  crypto: ^3.0.2
  get_it: ^8.0.3

  unicons: ^3.0.0
  eva_icons_flutter: ^3.1.0
  line_icons: ^2.0.1

  camera: ^0.11.0
  screen_brightness:
  # ffmpeg_kit_flutter_new: ^2.0.0
  ffmpeg_kit_16kb: ^1.0.3

  lottie: ^3.3.1
  # move_to_background: ^1.0.2
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  wechat_assets_picker: ^9.3.3
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.1
  qr_flutter: ^4.0.0
  qr_code_scanner_plus: ^2.0.10+1
  # qr_code_scanner: ^1.0.1
  pretty_qr_code: ^3.3.0
  shared_preferences: ^2.0.15
  expandable_text: ^2.3.0
  # connectivity_plus: ^6.0.3
  # flutter_dotenv: ^5.0.2
  contacts_service_plus: ^0.0.2
  shimmer: ^3.0.0
  photo_manager: ^2.4.0
  pin_code_fields: ^8.0.1

  flutter_linkify: ^6.0.0
  flutter_svg: ^2.0.2
  flutter_svg_provider: ^1.0.4
  flutter_switch: ^0.3.2
  flutter_cache_manager: ^3.3.0
  flutter_screenutil: ^5.5.3+2
  win32: ^5.14.0

  provider: ^6.0.3
  video_player: ^2.7.0
  audioplayers: ^6.5.0
  home_widget: ^0.8.0
  # receive_sharing_intent: ^1.8.1

  #  smooth_page_indicator:
  #    path: ./lib/features/home/helper/smooth_page_indicator-1.2.0+3/

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.2

dependency_overrides:
  json_annotation: ^4.7.0
  firebase_auth_web: ^5.3.0
  json_serializable: ^6.5.2
  change_app_package_name: ^1.1.0
  photo_manager: ^3.5.2
  extended_image: ^8.2.0
  http_client_helper: ^3.0.0
  http: ^0.13.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/gif/
    - assets/svg/
    - assets/audio/

  fonts:
    - family: sofia
      fonts:
        - asset: assets/fonts/sofia.otf
